# Generated by Django 5.2.11 on 2026-02-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='url_propiedad',
            field=models.URLField(blank=True, default='', help_text='URL de la foto principal', max_length=500),
        ),
    ]
