# Generated by Django 5.2.10 on 2026-02-21 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_inmueble_url_propiedad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='url_image',
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='url_propiedad',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='ImagenInmueble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='home.inmueble')),
            ],
            options={
                'ordering': ['orden'],
                'unique_together': {('inmueble', 'orden')},
            },
        ),
    ]
