# Generated by Django 5.2.10 on 2026-02-22 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_inmueble_url_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='asesor',
        ),
        migrations.RemoveField(
            model_name='perfilasesor',
            name='es_century',
        ),
        migrations.AddField(
            model_name='empresa',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='celular_captacion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='inmueble',
            name='nombre_captador',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_vencimiento_plan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='InmuebleGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guardado_en', models.DateTimeField(auto_now_add=True)),
                ('etiqueta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardados', to='home.etiqueta')),
                ('inmueble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.inmueble')),
            ],
            options={
                'unique_together': {('etiqueta', 'inmueble')},
            },
        ),
    ]
