# Generated by Django 5.2.11 on 2026-02-25 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_inmueble_asesor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.empresa'),
        ),
    ]
