# Generated by Django 5.2.10 on 2026-02-24 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_remove_inmueble_asesor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnálisisCMA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obj_titulo', models.CharField(default='Propiedad a valuar', max_length=200)),
                ('obj_cant_cuartos', models.PositiveIntegerField()),
                ('obj_cant_banios', models.PositiveIntegerField()),
                ('obj_area_construida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obj_area_terreno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('obj_parqueo', models.BooleanField(default=False)),
                ('obj_piscina', models.BooleanField(default=False)),
                ('obj_antiguedad', models.PositiveSmallIntegerField(help_text='Escala 1 (deteriorado) a 5 (nuevo/remodelado)')),
                ('obj_zona', models.CharField(blank=True, max_length=100)),
                ('obj_ciudad', models.CharField(blank=True, max_length=100)),
                ('resultado_json', models.JSONField(blank=True, null=True)),
                ('precio_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('precio_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('justificacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('comparable_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cma_comp1', to='home.inmueble')),
                ('comparable_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cma_comp2', to='home.inmueble')),
                ('comparable_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cma_comp3', to='home.inmueble')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis_cma', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Análisis CMA',
                'verbose_name_plural': 'Análisis CMA',
                'ordering': ['-creado_en'],
            },
        ),
    ]
